version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-data-base
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    networks:
      - mynet

  app:
    build: .
    container_name: my-bank
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: manager
      SPRING_DATASOURCE_PASSWORD: qwerty
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
